// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8O7Y0Q0nS43KfxrNYNZMWLi9c_n0xIwo',
    appId: '1:866761718494:web:56668fdeadc570657a604f',
    messagingSenderId: '866761718494',
    projectId: 'smartinventory39',
    authDomain: 'smartinventory39.firebaseapp.com',
    databaseURL: 'https://smartinventory39-default-rtdb.firebaseio.com',
    storageBucket: 'smartinventory39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZaZnUe8Vtr8M8fMM6kTqreYMuxIP-LI',
    appId: '1:866761718494:android:92e128ff099976d27a604f',
    messagingSenderId: '866761718494',
    projectId: 'smartinventory39',
    databaseURL: 'https://smartinventory39-default-rtdb.firebaseio.com',
    storageBucket: 'smartinventory39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXV1w40uYrcNKXmbjVHJWSJDt--Lue54',
    appId: '1:866761718494:ios:0d417852e0ab13e17a604f',
    messagingSenderId: '866761718494',
    projectId: 'smartinventory39',
    databaseURL: 'https://smartinventory39-default-rtdb.firebaseio.com',
    storageBucket: 'smartinventory39.appspot.com',
    iosClientId: '866761718494-2j95afqqeklph1c0np59lbofbdusv8fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaXV1w40uYrcNKXmbjVHJWSJDt--Lue54',
    appId: '1:866761718494:ios:e72dcb18db99bc807a604f',
    messagingSenderId: '866761718494',
    projectId: 'smartinventory39',
    databaseURL: 'https://smartinventory39-default-rtdb.firebaseio.com',
    storageBucket: 'smartinventory39.appspot.com',
    iosClientId: '866761718494-ni5lc0k3tkmf2el7hti5v5od96v4ve1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartInventory.RunnerTests',
  );
}
